name = "zzzzxzxzx"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "53899729-c001-462d-b024-d768f7aae585"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
